base:
  population_size: 50
  max_iterations: 10000
  mutation_rate: 0.01
  crossover_rate: 0.1
  elite_size: 0.1
  early_stop_iterations: 1000

func_optim:
  dimension: 2
  lower_bound: -5.12
  upper_bound: 5.12
  step_size: 0.5

TSP:
  tsp_file: "data/BEN30-XY.txt"