base:
  initial_temperature: 10000
  cooling_rate: 0.5
  max_iterations: 10000
  early_stop_iterations: 1000

func_optim:
  dimension: 2
  lower_bound: -5.12
  upper_bound: 5.12
  step_size: 1.0

TSP:
  tsp_file: "data/BEN30-XY.txt"